mysql << EOFMYSQL
use kk044;

DROP TABLE SONGS;
DROP TABLE RECORD_LABELS;
DROP TABLE ARTISTS;

CREATE TABLE ARTISTS(
	ARTIST_ID int NOT NULL,
	NAME char(50) NOT NULL,
	GENRE char(25) NOT NULL,
	PRIMARY KEY (ARTIST_ID)
);

CREATE TABLE RECORD_LABELS (
	LABEL_ID int NOT NULL, 
	LABEL_NAME char(50) NOT NULL,
	LABEL_CITY char(25) NOT NULL,
	DESIRED_GENRE char(25) NOT NULL, 
	PRIMARY KEY(LABEL_ID)
);

CREATE TABLE SONGS(
	SONG_ID int NOT NULL,
	ARTIST_ID int NOT NULL,
	LABEL_ID int NOT NULL,
	NAME char(50) NOT NULL,
	GENRE char(25) NOT NULL,
	YEAR int NOT NULL,
	RANKING int NOT NULL,
	PRIMARY KEY (SONG_ID),
	FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ARTIST_ID),
   	FOREIGN KEY (LABEL_ID) REFERENCES RECORD_LABELS(LABEL_ID)
);

INSERT INTO ARTISTS VALUES(23, 'Lil Uzi Vert', 'Rap'); 
INSERT INTO ARTISTS VALUES(14, 'Eagles', 'Rock');

INSERT INTO RECORD_LABELS VALUES(5481, 'Geffen', 'Santa Monica', 'Rock');
INSERT INTO RECORD_LABELS VALUES(4394, 'Atlantic Records','Philadelphia', 'Rap'); 

INSERT INTO SONGS VALUES(1, 23, 4394, 'Just Wanna Rock', 'Rap', '2022', 3); 
INSERT INTO SONGS VALUES(2, 14, 5481, 'Lyin Eyes', 'Rock', '1975', 87);

EOFMYSQL